FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/train.py src/
COPY service-account.json .

ENV PYTHONUNBUFFERED=1

CMD ["python", "src/train.py"]
